import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {

  const router = useRouter();

  const goToEvent = () =>
  {
     router.push("/event/evt_123"); 
  }

  return (
    <>
      <Head>
        <title>Book My Show</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
       <div className={styles.container}>
        <h1 className={styles.title}>Welcome to Real-Time Seat Booking</h1>
        <p className={styles.subtitle}>Book your seats instantly and watch availability update in real-time!</p>

         <button className={styles.button} onClick={goToEvent}>Go to Event</button>
       </div>
    </>
  );
}
